@baseUrl = http://localhost:8080

### Signup User
POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123!",
  "name": "testname"
}

### Login User
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123!"
}

> {%
  client.global.set("token", response.headers.valueOf("Authorization"));
%}

### Create Card
POST {{baseUrl}}/cards
Content-Type: application/json
Authorization: {{token}}

{
  "deckId": 3,
  "title": "New Card Title3",
  "description": "This is a description of the new card3",
  "startDate": "2024-07-10",
  "dueDate": "2024-07-20"
}

### Get Card
GET {{baseUrl}}/cards/33
Authorization: {{token}}

### Update Card
PUT {{baseUrl}}/cards/33
Content-Type: application/json
Authorization: {{token}}

{
  "title": "Updated Card Title",
  "description": "This is an updated description of the card",
  "startDate": "2024-07-15",
  "dueDate": "2024-07-25"
}

### Move Card
PATCH {{baseUrl}}/cards/33
Content-Type: application/json
Authorization: {{token}}

{
  "index": 0
}

### Delete Card
DELETE {{baseUrl}}/cards/1
Content-Type: application/json
Authorization: Bearer {{token}}